# Generated by Django 4.2.17 on 2025-04-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_billing_billingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='price_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('retail', 'Retail'), ('wholesale', 'Wholesale')], default='normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillingItem',
        ),
    ]
