# Generated by Django 4.2.17 on 2025-04-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(choices=[('Feedback', 'Feedback'), ('Complaint', 'Complaint'), ('Inquiry', 'Inquiry'), ('Other', 'Other')], max_length=50),
        ),
    ]
