# Generated by Django 4.2.17 on 2025-02-12 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail', '0002_rename_location_retailsellerprofile_store_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsellerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
