# Generated by Django 4.2.17 on 2025-02-15 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retail', '0003_alter_retailsellerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsellerprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retailsellerprofile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
