# Generated by Django 4.2.17 on 2025-02-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_alter_retailsellerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsellerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
