# Generated by Django 4.2.17 on 2025-03-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_alter_retailsellerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
